"""Generate docs/VALIDATION.md and docs/DATA.md from the pipeline's own outputs.

Nothing in these two files is typed by hand: they are rebuilt from
web/data/validation.json (written by lunarops.report after the tests) and from
data/manifest.yaml + the SHA-256 lock files, so the documentation cannot drift
from what the code actually did.

    python -m lunarops.report && python -m lunarops.docs
"""
from __future__ import annotations

import json

import yaml

from .paths import DATA, ROOT, WEB_DATA

DOCS = ROOT / "docs"


def _md_cell(s) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def validation_md() -> str:
    v = json.loads((WEB_DATA / "validation.json").read_text())
    rows = "\n".join(f"| {_md_cell(c['check'])} | {_md_cell(c['reference'])} | {_md_cell(c['result'])} | {_md_cell(c['criterion'])} | **{c['status']}** |"
                     for c in v["checks"])
    return f"""# Validation results

Generated by `python -m lunarops.docs` from `web/data/validation.json`, which `lunarops.report` writes from the
test suite (`python -m pytest`). Pass criteria were fixed before each check was run (decision D-019), except where a
row says *indicative*. A FAIL would be reported here as a FAIL.

| Check | Reference | Our result | Pass criterion | Status |
|---|---|---|---|---|
{rows}

Also verified on every build:

* `web/tests/golden.html` — the browser engine (`web/engine.js`) and the Python solver (`pipeline/lunarops/solver.py`)
  agree on every metric of 6 requirement sets × 6 sites (max difference 5·10⁻¹⁰, 0 mismatches), and the landing-error
  ensemble's centre point reproduces the main series exactly (link, blackout, darkness).
* Unit tests: projection round trips against the GeoTIFF georeferencing, the solar-disc segment formula, run-length
  logic, minimal relaxation, the SPICE surface-observer shortcut (< 10⁻³° vs `azlcpo`).
"""


def data_md() -> str:
    man = yaml.safe_load((DATA / "manifest.yaml").read_text())
    lock = json.loads((DATA / "manifest.lock.json").read_text()) if (DATA / "manifest.lock.json").exists() else {}
    tiles = json.loads((DATA / "tiles.lock.json").read_text()) if (DATA / "tiles.lock.json").exists() else {}
    rows = []
    for f in man["files"]:
        how = "HTTP range (tiles/rows only)" if f.get("range_only") else "whole file"
        pin = lock.get(f["id"], {}).get("sha256", "")
        pin = f"`{pin[:16]}…`" if pin else ("per range, see `tiles.lock.json`" if f.get("range_only") else "—")
        rows.append(f"| `{f['id']}` | [{f['url'].rsplit('/', 1)[-1]}]({f['url']}) | {f['size'] / 1e6:,.1f} MB | {how} | {pin} | {_md_cell(f['role'])} |")
    cites = "\n".join(f"* {c}" for c in man.get("citations", []))
    return f"""# Data sources

Generated by `python -m lunarops.docs` from `data/manifest.yaml`. Every input file, where it comes from, and how it is
pinned. Large DEMs are never downloaded whole: `lunarops.dem` reads only the tiles or rows a horizon needs and records
a SHA-256 for every byte range ({len(tiles)} ranges pinned in `data/tiles.lock.json`), so a rerun uses identical bytes
or stops with an error.

All inputs are public NASA / JPL products (US Government works); no API keys are used.

| id | File | Size | Read as | SHA-256 | Role |
|---|---|---|---|---|---|
{chr(10).join(rows)}

Additionally, the DEM error clones of PGDA product 78 (`https://pgda.gsfc.nasa.gov/data/LOLA_5mpp/<Site>/Clones/`)
are read per site (`tools/get_clones.py` downloads them; `lunarops.clones` processes them). JPL Horizons tables used
by the tests are stored in `pipeline/tests/fixtures/`.

## Citations
{cites}
"""


def main():
    DOCS.mkdir(exist_ok=True)
    (DOCS / "VALIDATION.md").write_text(validation_md(), encoding="utf-8")
    (DOCS / "DATA.md").write_text(data_md(), encoding="utf-8")
    print("wrote", DOCS / "VALIDATION.md", DOCS / "DATA.md")


if __name__ == "__main__":
    main()
